### ISSUE TITLE
Errors in bp-gsi-overloading.md

### ISSUE THREAD

**Issue by nyh** [awsdocs/amazon-dynamodb-developer-guide#202]
Unless I'm missing something, the example in bp-gsi-overloading.md has one serious error, and a couple of cases of confusing terminology:

The error is to suggest that the user should create an index with the base table's sort key as the partition key, and "Data" as the sort key. I think it should be the other way around! I.e., "Data" should be the index's partition key, and the sort key the same as in the base table. In this example, the table's original sort key only has a few different values, so it is a bad choice for a partition key. At the same time, the "Data" string has many different values, so it's a good choice for the partition key.

The smaller points:

- You keep repeating that the different Data values have different "types". They don't... They are all strings - and that's important for this technique to work. Even the dollar amount is a string like "$5,477" and not a number. This trick wouldn't have worked if some items had non-string data.

- Please give the base table's Sort Key a name - it makes it hard to refer to that attribute without a name, and anyway, even key attributes have names.

**Comment by NicholasDunham** [comment]
Thanks for your input on this. I see your point about the base table's sort key having relatively few values, but I think the GSI suggested in the best practices docs has a couple of advantages nonetheless. Specifically, the queries described in the bullet points at the end of the page wouldn't be possible if "Data" were used as the partition key:

- Looking up an employee by name would work fine. We'd just search for the employee's name in the partition key and "Employee_Name" in the sort key.
- We couldn't find all employees working in a specific warehouse because we wouldn't know what to look for in the partition key.
- We couldn't easily get a list of recent hires because we can't look for a range of dates in the partition key, as we can in the sort key.

I certainly take your other points. I note that the last paragraph before the table image refers to "kinds of data" rather than "types of data," which seems to me like a less confusing term here (though admittedly still overloaded). Do you agree, or do you have a better suggestion?
