### ISSUE TITLE
Outdated TryDaxHelper.java

### ISSUE THREAD

**Issue by pchrzasz** [awsdocs/amazon-dynamodb-developer-guide#31]
Hello,

I must say that I am really disappointed and will never use your solution on production because your documentation says a lot about you. First of all, I wanted to check how is DAX working with dynamodb, but of course I could not, because I cannot find any example how create Dax cluster. When I found I see that it is outdated with API even from january this year (sic!).

Simple outdated example:
https://github.com/awsdocs/amazon-dynamodb-developer-guide/blob/master/doc_source/DAX.client.run-application-java.TryDaxHelper.md

**Comment by ghost** [comment]
Why not try submitting a pull request to update the docs?

**Comment by pchrzasz** [comment]
Maybe because I still have not found any answer for my question?

**Comment by ghost** [comment]
I don't see where you asked a question

**Comment by santisra** [comment]
@pchrzasz Hi thanks for your feedback. That code is part of a [tutorial](https://github.com/awsdocs/amazon-dynamodb-developer-guide/blob/master/doc_source/DAX.client.sample-app.md) that states "In order to complete this tutorial, you must have a DAX cluster running in your default VPC. If you have not yet created a DAX cluster, see [Creating a DAX Cluster for instructions](https://github.com/awsdocs/amazon-dynamodb-developer-guide/blob/master/doc_source/DAX.create-cluster.md). "

This section contains information about how to create a cluster using the CLI or the console. I'll add to the backlog to add an example using the API/update the code samples. Please let me know if this helps you out.
Thanks!

**Comment by pchrzasz** [comment]
@santisra Thanks for your reply. I see that you are more helpful than @darrenhgc 
But it still does not solve my problem because I already have an app using dynamodb. I found something like this:
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.client.modify-your-app.html
There is written "Modifying an Existing Application to Use DAX ". But this code is not working because of compilation error. API is outdated. For example:
`ClientConfig daxConfig = new ClientConfig().withEndpoints("mydaxcluster.2cmrwl.clustercfg.dax.use1.cache.amazonaws.com:8111").withRegion("us-east-1");
AmazonDaxClient client = new ClusterDaxClient(daxConfig);`
Method `withEndpoints` is not exsiting. `ClusterDaxClient` also. 

I want to use DAX in exsiting application configuring it from app code, not using console. Do you have any working example? Even in API I have not found any example.

BR,
Paweł

**Comment by asad-awadia** [comment]
@santisra The docs suggest that the Dax client can just be used as an AmazonDynamoDB client but the types are not valid anymore
```
val client: AmazonDynamoDB = daxClientBuilder.build()
    return DynamoDB(client)
```
Both these two lines are compile time errors

**Comment by NicholasDunham** [comment]
These code samples have been updated since this issue was opened, so I'm closing it. Feel free to reopen the issue if problems remain.
